/*************************************************************************
 * This file was generated by CRUST by an automated semantics preserving
 * translation from C/C++ to Rust
 * CRUST isn't perfect and may require manual editing
 * Check warnings and errors and refer to the official Rust Documentation
 ************************************************************************/

/** Crust doesn't resolve C/C++ dependencies or included header.
* You may have to define your own module and implement those functionality in Rust
* Or you can translate header file with Crust to produce Rust code. *
* >>>>>>>> # include < iostream >
 **/
fn main() { /*
            Wypisz na konsole swoje inicjaly.
            */
    std :: 
//This statement need to be handled manually 
 cout << "A.D."
        << std::endl; /*
                      Wypisz na konsole "witaj swiecie"
                      */
    std :: 
//This statement need to be handled manually 
 cout << "Witaj swiecie"
        << std::endl;
    /** Crust tries to identify return statement and replace with rust equivalent
     * shorthand notation. If error found in this line, Please replace shorthand notation
     * with return statement
     **/
    return 0;
}
